name: Integration tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - "*"
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - "*"

jobs:
  integration:
    name: Integ
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: ["opendistro", "opensearch"]
        secured: ["true", "false"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: "./.ci/run-tests ${{ matrix.cluster }} ${{ matrix.secured }}"
        name: Integ ${{ matrix.stack_version }} ${{ matrix.cluster }} secured=${{ matrix.secured }}
